[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
security_oracle = "SoLGuaRD11111111111111111111111111111111111"
validator_registry = "VaLiDaToR11111111111111111111111111111111111"
transparency_vault = "TrAnSpArEnCy1111111111111111111111111111111"
governance_module = "GoVeRnAnCe1111111111111111111111111111111111"

[programs.devnet]
security_oracle = "SoLGuaRD11111111111111111111111111111111111"
validator_registry = "VaLiDaToR11111111111111111111111111111111111"
transparency_vault = "TrAnSpArEnCy1111111111111111111111111111111"
governance_module = "GoVeRnAnCe1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
